name: Generate README.md

on:
  push:
    branches:
      - master
    paths:
      - 'README.md.template'
  workflow_dispatch:

concurrency: readme

defaults:
  run:
    shell: bash --login {0}

permissions:
  contents: write

jobs:
  run-templating:
    runs-on: ubuntu-latest
    steps:
      - uses: EffortGames/action-setup-bash@v1
      - uses: actions/checkout@v2
      - uses: EffortGames/action-template@v1
        with:
          source: 'README.md.template'
          target: 'README.md'
      - run: |
          # git config, git add, git commit, git push
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit --no-verify -m "Regenerate README.md"
          
          # rebase and push in a retry loop
          for i in {1..50}; do
            git pull --rebase && git push && break || sleep 1
          done
